const jets = [
  // 1–30 (already sent)
  { name: "J20", type: "Fighter", weapons: ["PL‑12", "PL‑10", "Type 99 cannon"], description: "Chinese stealth multirole fighter." },
  { name: "F101", type: "Fighter", weapons: ["AIM‑9 Sidewinder", "AIM‑7 Sparrow", "M61 Vulcan"], description: "Early Cold War US jet fighter." },
  { name: "F4 Phantom", type: "Fighter", weapons: ["AIM‑7 Sparrow", "AIM‑9 Sidewinder", "M61 Vulcan", "Mk 82/84 bombs"], description: "US multirole jet used in Vietnam War." },
  { name: "A10", type: "Attack", weapons: ["GAU‑8/A Avenger 30mm cannon", "AGM‑65 Maverick", "Hydra 70 rockets", "GBU‑12 Paveway II"], description: "Close air support aircraft (Warthog)." },
  { name: "F22", type: "Fighter", weapons: ["AIM‑120 AMRAAM", "AIM‑9 Sidewinder", "M61A2 Vulcan"], description: "Stealth air superiority fighter." },
  { name: "F53A", type: "Fighter", weapons: ["AIM‑9 Sidewinder", "AIM‑120 AMRAAM", "M61 Vulcan"], description: "Advanced experimental fighter." },
  { name: "F35B", type: "Fighter", weapons: ["GAU‑22/A 25mm cannon", "AIM‑120 AMRAAM", "AIM‑9X Sidewinder", "GBU‑12 Paveway II"], description: "STOVL stealth multirole fighter." },
  { name: "F35C", type: "Fighter", weapons: ["GAU‑22/A 25mm cannon", "AIM‑120 AMRAAM", "AIM‑9X Sidewinder", "GBU‑12 Paveway II"], description: "Carrier variant stealth fighter." },
  { name: "YF23", type: "Fighter", weapons: ["AIM‑120 AMRAAM", "AIM‑9 Sidewinder", "M61 Vulcan"], description: "Prototype stealth fighter, competitor to F22." },
  { name: "MiG15", type: "Fighter", weapons: ["NR‑23 23mm cannon", "RS‑82 rockets"], description: "Early Soviet jet fighter." },
  { name: "MiG17", type: "Fighter", weapons: ["NR‑23 23mm cannon", "R‑3S (AA‑2 Atoll)"], description: "Soviet fighter used in Vietnam War." },
  { name: "Me262", type: "Fighter", weapons: ["MK‑108 30mm cannon", "R4M rockets"], description: "First operational jet fighter (WW2 Germany)." },
  { name: "Hawk 200", type: "Trainer/Light Attack", weapons: ["ADEN 30mm cannon", "AS‑30 missiles"], description: "Light attack/trainer jet." },
  { name: "MiG19", type: "Fighter", weapons: ["NR‑30 30mm cannon", "R‑3S missile"], description: "Soviet supersonic jet fighter." },
  { name: "Su57", type: "Fighter", weapons: ["R‑77", "R‑73", "30mm cannon"], description: "Russian stealth multirole fighter." },
  { name: "Su33", type: "Fighter", weapons: ["R‑73", "R‑77", "GSh‑30‑1 30mm cannon"], description: "Russian carrier‑based fighter." },
  { name: "Su27", type: "Fighter", weapons: ["R‑27", "R‑73", "GSh‑30‑1 30mm cannon"], description: "Russian air superiority fighter." },
  { name: "F15", type: "Fighter", weapons: ["AIM‑7 Sparrow", "AIM‑120 AMRAAM", "AIM‑9 Sidewinder", "M61A1 Vulcan"], description: "US air superiority fighter." },
  { name: "F16", type: "Fighter", weapons: ["M61 Vulcan 20mm cannon", "AIM‑9 Sidewinder", "AIM‑120 AMRAAM", "AGM‑65 Maverick"], description: "US multirole fighter." },
  { name: "F17", type: "Fighter", weapons: ["M61 Vulcan", "AIM‑9 Sidewinder"], description: "Prototype/experimental fighter." },
  { name: "F18", type: "Fighter", weapons: ["M61A1 Vulcan", "AIM‑9 Sidewinder", "AIM‑120 AMRAAM", "GBU‑12 Paveway II"], description: "US multirole carrier fighter." },
  { name: "F18 Super Hornet", type: "Fighter", weapons: ["M61A1 Vulcan", "AIM‑9 Sidewinder", "AIM‑120 AMRAAM", "GBU‑12 Paveway II"], description: "Larger, upgraded F18." },
  { name: "Ching Kuo IDF", type: "Fighter", weapons: ["AIM‑9 Sidewinder", "Sky Sword II", "M61 Vulcan"], description: "Taiwanese fighter jet." },
  { name: "F14", type: "Fighter", weapons: ["AIM‑54 Phoenix", "AIM‑7 Sparrow", "AIM‑9 Sidewinder", "M61 Vulcan"], description: "US carrier fighter with variable geometry wings." },
  { name: "AMX International AMX", type: "Attack", weapons: ["Mk 82/84 bombs", "AGM‑65 Maverick", "DEFA 30mm cannon"], description: "Italian‑Brazilian attack jet." },
  { name: "M.B.326GB", type: "Trainer", weapons: ["Breda 12.7mm cannon"], description: "Italian jet trainer." },
  { name: "F117", type: "Attack", weapons: ["GBU‑10 Paveway II", "GBU‑12 Paveway II"], description: "US stealth attack aircraft." },
  { name: "F111", type: "Attack", weapons: ["GBU‑10/12 Paveway II", "AGM‑65 Maverick"], description: "US tactical bomber." },
  { name: "L392A", type: "Transport", weapons: [], description: "Light transport aircraft." },
  { name: "Super Etendard", type: "Attack", weapons: ["Exocet missile", "Mk 82 bombs"], description: "French carrier strike jet." },

  // **51–60 will continue below**
  { name: "CM.170", type: "Trainer/Attack", weapons: ["20mm cannon", "Light rockets"], description: "French light jet trainer/attack." },
  { name: "Dassault Mirage 3", type: "Fighter", weapons: ["R550 Magic", "DEFA 30mm cannon"], description: "French delta‑wing fighter." },
  { name: "Dassault Mirage 5/50", type: "Fighter", weapons: ["Magic missiles", "DEFA 30mm"], description: "Advanced Mirage 3 attack variant." },
  { name: "CF105", type: "Fighter", weapons: ["AIR‑2 Genie", "AIM‑4 Falcon"], description: "Canadian delta‑wing interceptor (Avro Arrow)." },
  { name: "Dassault Mirage F1", type: "Fighter", weapons: ["Magic missiles", "DEFA 30mm"], description: "French multirole fighter." },
  { name: "Dassault Mirage 2000", type: "Fighter", weapons: ["MICA missiles", "DEFA 30mm"], description: "French high‑performance fighter." },
  { name: "British Harrier Series", type: "Fighter/Attack", weapons: ["Sidewinder", "Rockeye II bombs", "30mm ADEN cannon"], description: "VTOL/Harrier jump jets." },
  { name: "IAI Kfir", type: "Fighter", weapons: ["Python 4/5", "Shafrir missiles", "M61 Vulcan"], description: "Israeli multirole fighter." },
  { name: "P80", type: "Fighter", weapons: [".50 cal machine guns"], description: "Early US jet fighter." },
  { name: "F86", type: "Fighter", weapons: [".50 cal machine guns", "HVAR rockets"], description: "Korean War US jet fighter." },
  { name: "Pavana Tornado", type: "Fighter/Bomber", weapons: ["Tornado missiles", "Paveway bombs"], description: "Strike fighter (Italy)." },
  { name: "F84", type: "Fighter/Bomber", weapons: [".50 cal machine guns", "Bombs"], description: "Early US jet fighter/bomber." },
  { name: "Jaguar", type: "Attack", weapons: ["Jaguar missiles", "30mm cannon"], description: "Ground‑attack jet." },
  { name: "P59B", type: "Fighter", weapons: [".50 cal machine guns"], description: "One of the first US jet fighters." },
  { name: "Su24", type: "Attack", weapons: ["Kh‑25", "Kh‑29 missiles", "S‑24 rockets"], description: "Soviet strike aircraft." },
  { name: "Su25", type: "Attack", weapons: ["GSh‑30‑2 30mm cannon", "Kh‑25 missiles", "S‑8 rockets"], description: "Russian close air support jet." },
  { name: "S.2B", type: "Trainer/Patrol", weapons: ["20mm cannon"], description: "Carrier trainer/patrol aircraft." },
  { name: "F102", type: "Fighter", weapons: ["AIM‑4 Falcon", "AIM‑26 Falcon"], description: "US delta‑wing interceptor." },
  { name: "F106", type: "Fighter", weapons: ["AIM‑4 Falcon", "AIM‑26 Falcon"], description: "Advanced US interceptor." },
  { name: "F94", type: "Fighter", weapons: ["AIM‑4 Falcon"], description: "Early jet interceptor." },
  { name: "F5 Tiger", type: "Fighter", weapons: ["AIM‑9 Sidewinder", "M39 cannon"], description: "US lightweight fighter." },
  { name: "F104", type: "Fighter", weapons: ["AIM‑9 Sidewinder", "M61 Vulcan"], description: "US supersonic fighter." },
  { name: "MiG21", type: "Fighter", weapons: ["R‑3S", "GSh‑23 cannon"], description: "Soviet supersonic fighter." },
  { name: "MiG25", type: "Fighter", weapons: ["R‑40 missiles", "GSh‑6‑23 cannon"], description: "Soviet interceptor/fighter." },

  // **100–110 next**

