const jets = [
  { name: "J20", type: "", weapons: [], description: "" },
  { name: "F101", type: "", weapons: [], description: "" },
  { name: "F4 Phantom", type: "", weapons: [], description: "" },
  { name: "A10", type: "", weapons: [], description: "" },
  { name: "F22", type: "", weapons: [], description: "" },
  { name: "F53A", type: "", weapons: [], description: "" },
  { name: "F35B", type: "", weapons: [], description: "" },
  { name: "F35C", type: "", weapons: [], description: "" },
  { name: "YF23", type: "", weapons: [], description: "" },
  { name: "MiG15", type: "", weapons: [], description: "" },
  { name: "MiG17", type: "", weapons: [], description: "" },
  { name: "Me262", type: "", weapons: [], description: "" },
  { name: "Hawk 200", type: "", weapons: [], description: "" },
  { name: "MiG19", type: "", weapons: [], description: "" },
  { name: "Su57", type: "", weapons: [], description: "" },
  { name: "Su33", type: "", weapons: [], description: "" },
  { name: "Su27", type: "", weapons: [], description: "" },
  { name: "F15", type: "", weapons: [], description: "" },
  { name: "F16", type: "", weapons: [], description: "" },
  { name: "F17", type: "", weapons: [], description: "" },
  { name: "F18", type: "", weapons: [], description: "" },
  { name: "F18 Super Hornet", type: "", weapons: [], description: "" },
  { name: "Ching Kuo IDF", type: "", weapons: [], description: "" },
  { name: "F14", type: "", weapons: [], description: "" },
  { name: "AMX International AMX", type: "", weapons: [], description: "" },
  { name: "M.B.326GB", type: "", weapons: [], description: "" },
  { name: "F117", type: "", weapons: [], description: "" },
  { name: "F111", type: "", weapons: [], description: "" },
  { name: "L392A", type: "", weapons: [], description: "" },
  { name: "Super Etendard", type: "", weapons: [], description: "" },
  { name: "CM.170", type: "", weapons: [], description: "" },
  { name: "Dassault Mirage 3", type: "", weapons: [], description: "" },
  { name: "Dassault Mirage 5/50", type: "", weapons: [], description: "" },
  { name: "CF105", type: "", weapons: [], description: "" },
  { name: "Dassault Mirage F1", type: "", weapons: [], description: "" },
  { name: "Dassault Mirage 2000", type: "", weapons: [], description: "" },
  { name: "British Harrier Series", type: "", weapons: [], description: "" },
  { name: "IAI Kfir", type: "", weapons: [], description: "" },
  { name: "P80", type: "", weapons: [], description: "" },
  { name: "F86", type: "", weapons: [], description: "" },
  { name: "Pavana Tornado", type: "", weapons: [], description: "" },
  { name: "F84", type: "", weapons: [], description: "" },
  { name: "Jaguar", type: "", weapons: [], description: "" },
  { name: "P59B", type: "", weapons: [], description: "" },
  { name: "Su24", type: "", weapons: [], description: "" },
  { name: "Su25", type: "", weapons: [], description: "" },
  { name: "S.2B", type: "", weapons: [], description: "" },
  { name: "F102", type: "", weapons: [], description: "" },
  { name: "F106", type: "", weapons: [], description: "" },
  { name: "F94", type: "", weapons: [], description: "" },
  { name: "F5 Tiger", type: "", weapons: [], description: "" },
  { name: "F104", type: "", weapons: [], description: "" },
  { name: "MiG21", type: "", weapons: [], description: "" },
  { name: "MiG25", type: "", weapons: [], description: "" },
  { name: "MiG29", type: "", weapons: [], description: "" },
  { name: "J10", type: "", weapons: [], description: "" },
  { name: "F105", type: "", weapons: [], description: "" },
  { name: "J35 Draken", type: "", weapons: [], description: "" },
  { name: "Chinese J35", type: "", weapons: [], description: "" },
  { name: "Su7", type: "", weapons: [], description: "" },
  { name: "Su17", type: "", weapons: [], description: "" },
  { name: "Su20", type: "", weapons: [], description: "" },
  { name: "Su22", type: "", weapons: [], description: "" },
  { name: "A7", type: "", weapons: [], description: "" },
  { name: "F8", type: "", weapons: [], description: "" },
  { name: "IAI C1", type: "", weapons: [], description: "" },
  { name: "YF22", type: "", weapons: [], description: "" },
  { name: "Me163", type: "", weapons: [], description: "" },
  { name: "MiG23", type: "", weapons: [], description: "" },
  { name: "MiG31", type: "", weapons: [], description: "" },
  { name: "SR.53", type: "", weapons: [], description: "" },
  { name: "J6", type: "", weapons: [], description: "" },
  { name: "Su15", type: "", weapons: [], description: "" },
  { name: "Su35", type: "", weapons: [], description: "" },
  { name: "Su30", type: "", weapons: [], description: "" },
  { name: "Yak28/Yak38", type: "", weapons: [], description: "" },
  { name: "Yak41", type: "", weapons: [], description: "" },
  { name: "J16", type: "", weapons: [], description: "" },
  { name: "J11", type: "", weapons: [], description: "" },
  { name: "J35", type: "", weapons: [], description: "" },
  { name: "J15", type: "", weapons: [], description: "" },
  { name: "F151", type: "", weapons: [], description: "" },
  { name: "F161", type: "", weapons: [], description: "" },
  { name: "F851", type: "", weapons: [], description: "" },
  { name: "MF1", type: "", weapons: [], description: "" },
  { name: "MF2", type: "", weapons: [], description: "" }
];

